//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarchProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarchQuality
    {
        public System.DateTime AddTime { get; set; }
        public Nullable<double> PH { get; set; }
        public Nullable<double> Whiteness { get; set; }
        public Nullable<double> Viscosity { get; set; }
        public Nullable<double> SulfurResidue { get; set; }
    }
}
